name: GitHub Actions demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  test:
    name: Test workflow
    uses: ./.github/workflows/dummy.yml
    secrets: inherit
